
[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  # These will be set via .env in development and via Netlify UI in production
  MONGODB_URI = "mongodb+srv://rishigajera9128:xxVbGMDiM9uP8G7H@cluster0.pc9bym4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET = "7156b8d9eb946271aab3282c2889e208614d62364e2f96682d0f64183cb51a93f6af04b0f3349e926919a36e19fb19a0d0bcb06d30eee912bf5e41543f505001"
